/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-tint": "#4d44e3",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "on-primary-container": "#dad7ff",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "error": "#ba1a1a",
        "inverse-primary": "#c3c0ff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        "secondary-container": "#dae2fd",
        "on-tertiary": "#ffffff",
        "background": "#f8f9ff",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-secondary": "#ffffff",
        "surface": "#f8f9ff",
        "primary": "#3525cd",
        "primary-hover": "#2f1fb8",
        "primary-fixed": "#e2dfff",
        "tertiary-container": "#4b4dd8",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "on-surface": "#0b1c30",
        "outline": "#777587",
        "primary-fixed-dim": "#c3c0ff",
        "on-error": "#ffffff",
        "on-surface-variant": "#464555",
        "outline-variant": "#c7c4d8",
        "primary-container": "#4f46e5",
        "tertiary": "#3130c0",
        "inverse-surface": "#213145",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-container": "#5c647a",
        "secondary": "#565e74",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#dae2fd",
        "on-primary-fixed": "#0f0069",
        "on-tertiary-container": "#d9d8ff",
        "on-tertiary-fixed": "#07006c",
        "on-primary-fixed-variant": "#3323cc",
        "secondary-fixed-dim": "#bec6e0",
        "sidebar-border": "#1e293b",
        "line": "#e2e8f0",
        "line-strong": "#cbd5e1",
        "risk-low": "#10b981",
        "risk-low-tint": "#ecfdf5",
        "risk-low-border": "#a7f3d0",
        "risk-low-text": "#065f46",
        "risk-moderate": "#f59e0b",
        "risk-moderate-tint": "#fffbeb",
        "risk-moderate-border": "#fde68a",
        "risk-moderate-text": "#92400e",
        "risk-high": "#f97316",
        "risk-high-tint": "#fff7ed",
        "risk-high-border": "#ffedd5",
        "risk-high-text": "#9a3412",
        "risk-critical": "#ef4444",
        "risk-critical-tint": "#fef2f2",
        "risk-critical-border": "#fecaca",
        "risk-critical-text": "#991b1b",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-base": "1.0rem",
        "space-2xl": "3.0rem",
        "space-lg": "1.5rem",
        "panel-max-width": "90rem",
        "space-xl": "2.0rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "gutter": "1.25rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "sidebar-width": "17.5rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "data-metric": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "monospace"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", fontWeight: "400" }],
        "data-metric": ["1.5rem", { lineHeight: "1.75rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["0.75rem", { lineHeight: "1.0rem", letterSpacing: "0.025em", fontWeight: "600" }],
        "data-mono": ["0.8125rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "headline-lg": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "display-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["0.875rem", { lineHeight: "1.375rem", fontWeight: "400" }],
        "headline-xl": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["1.0rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "500" }],
        "body-lg": ["1.0rem", { lineHeight: "1.625rem", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
