"""Initial VIORA schema — contract §8, all 15 entities.

Hand-written to match app/models.py exactly rather than autogenerated, so the
first revision is reviewable against the contract table by table.

Append-only tables (Report, InteractionAnalysis, RiskAssessment, RiskPrediction,
WorkflowEvent) carry no UPDATE trigger — append-only is enforced in the service
layer, deliberately: a database-level guard would also block the legitimate
`Alert.report_id` backfill when a mid-conversation URGENT alert is later linked
to its report.

Revision ID: 0001_initial
Revises: None
Create Date: 2026-09-06

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------------------------------------------------------------- users --
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("uid", sa.String(length=32), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("preferred_language", sa.String(length=8), nullable=False, server_default="hi"),
        sa.Column("preferred_channel", sa.String(length=16), nullable=False, server_default="TEXT"),
        sa.Column("safe_contact_start", sa.String(length=5), nullable=False, server_default="10:00"),
        sa.Column("safe_contact_end", sa.String(length=5), nullable=False, server_default="18:00"),
        sa.Column("timezone", sa.String(length=64), nullable=False, server_default="Asia/Kolkata"),
        # Internal only. Never rendered, always excluded from aggregates.
        sa.Column("is_controlled_test", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_users_uid", "users", ["uid"], unique=True)

    # ------------------------------------------------------------- consents --
    op.create_table(
        "consents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=16), nullable=False, server_default="1.0.0"),
        sa.Column(
            "audio_retention_opt_in", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_consents_user_id", "consents", ["user_id"])

    # ---------------------------------------------------------- staff_users --
    op.create_table(
        "staff_users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False, server_default="DSWO"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_staff_users_email", "staff_users", ["email"], unique=True)

    # ---------------------------------------------------------------- cases --
    op.create_table(
        "cases",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("case_ref", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="ACTIVE"),
        sa.Column("legal_stage", sa.String(length=64), nullable=True),
        sa.Column("assigned_staff_id", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["assigned_staff_id"], ["staff_users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_cases_user_id", "cases", ["user_id"])
    op.create_index("ix_cases_case_ref", "cases", ["case_ref"], unique=True)

    # --------------------------------------------------------- interactions --
    op.create_table(
        "interactions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False, server_default="TEXT"),
        sa.Column("language", sa.String(length=8), nullable=False, server_default="hi"),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="IN_PROGRESS"),
        sa.Column("turn_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_interactions_case_id", "interactions", ["case_id"])

    # ------------------------------------------------ conversation_messages --
    op.create_table(
        "conversation_messages",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("interaction_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=8), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("interaction_id", "seq", name="uq_message_seq"),
    )
    op.create_index(
        "ix_conversation_messages_interaction_id", "conversation_messages", ["interaction_id"]
    )

    # ------------------------------------------------- interaction_analyses --
    # APPEND ONLY.
    op.create_table(
        "interaction_analyses",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("interaction_id", sa.Integer(), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False, server_default="1.0.0"),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_interaction_analyses_interaction_id", "interaction_analyses", ["interaction_id"]
    )

    # -------------------------------------------------------------- reports --
    # APPEND ONLY, versioned per case.
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("interaction_id", sa.Integer(), nullable=True),
        sa.Column("report_version", sa.Integer(), nullable=False),
        # Two axes, never merged into one stored band.
        sa.Column("distress_score", sa.Float(), nullable=False),
        sa.Column("threat_score", sa.Float(), nullable=False),
        sa.Column("composite_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("baseline_score", sa.Float(), nullable=False),
        sa.Column("baseline_confidence", sa.String(length=8), nullable=False),
        sa.Column("previous_score", sa.Float(), nullable=True),
        sa.Column("score_change", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("baseline_deviation", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("trend", sa.String(length=24), nullable=False),
        sa.Column("signals_snapshot", sa.JSON(), nullable=False),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("conversation_summary", sa.Text(), nullable=True),
        sa.Column("scoring_version", sa.String(length=16), nullable=False, server_default="1.0.0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("case_id", "report_version", name="uq_report_case_version"),
    )
    op.create_index("ix_reports_case_id", "reports", ["case_id"])
    op.create_index("ix_reports_interaction_id", "reports", ["interaction_id"])
    op.create_index("ix_reports_case_created", "reports", ["case_id", "created_at"])

    # ----------------------------------------------------- risk_assessments --
    # APPEND ONLY.
    op.create_table(
        "risk_assessments",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column("distress_score", sa.Float(), nullable=False),
        sa.Column("threat_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_risk_assessments_case_id", "risk_assessments", ["case_id"])
    op.create_index("ix_risk_assessments_report_id", "risk_assessments", ["report_id"])

    # ----------------------------------------------------- risk_predictions --
    # APPEND ONLY.
    op.create_table(
        "risk_predictions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("escalation_risk", sa.Float(), nullable=False),
        sa.Column(
            "horizon", sa.String(length=32), nullable=False, server_default="NEXT_2_CHECKINS"
        ),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False, server_default="1.0.0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_risk_predictions_case_id", "risk_predictions", ["case_id"])
    op.create_index("ix_risk_predictions_report_id", "risk_predictions", ["report_id"])

    # --------------------------------------------------------------- alerts --
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        # Nullable: an URGENT alert is written mid-interaction, before a report
        # exists. Contract §6 / §7.
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("interaction_id", sa.Integer(), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="OPEN"),
        sa.Column("factors", sa.JSON(), nullable=False),
        sa.Column("acknowledged_by", sa.Integer(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["staff_users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_alerts_case_id", "alerts", ["case_id"])

    # -------------------------------------------------------- human_reviews --
    op.create_table(
        "human_reviews",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["alert_id"], ["alerts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["staff_id"], ["staff_users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_human_reviews_case_id", "human_reviews", ["case_id"])

    # --------------------------------------------------------- interventions --
    op.create_table(
        "interventions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("review_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="OPEN"),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["human_reviews.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["staff_id"], ["staff_users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_interventions_case_id", "interventions", ["case_id"])

    # ------------------------------------------------------------ follow_ups --
    op.create_table(
        "follow_ups",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False, server_default="TEXT"),
        sa.Column("status", sa.String(length=16), nullable=False, server_default="SCHEDULED"),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False, server_default="1.0.0"),
        # The interval is predicted per conversation, not read off a band table.
        # These columns record how the date was arrived at, so the dashboard can
        # answer "why this date?" and a counsellor can override it.
        sa.Column("source", sa.String(length=16), nullable=False, server_default="PREDICTED"),
        sa.Column("cadence_hours", sa.Float(), nullable=True),
        sa.Column("cadence_base_hours", sa.Float(), nullable=True),
        sa.Column("cadence_factors", sa.JSON(), nullable=True),
        sa.Column("cadence_version", sa.String(length=16), nullable=True),
        sa.Column("scheduled_by_staff_id", sa.Integer(), nullable=True),
        sa.Column("staff_note", sa.Text(), nullable=True),
        sa.Column("completed_interaction_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scheduled_by_staff_id"], ["staff_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["completed_interaction_id"], ["interactions.id"], ondelete="SET NULL"
        ),
    )
    op.create_index("ix_follow_ups_case_id", "follow_ups", ["case_id"])
    # The scheduler's sweep query: status + scheduled_for.
    op.create_index("ix_followups_due", "follow_ups", ["status", "scheduled_for"])

    # -------------------------------------------------------- workflow_events --
    # APPEND ONLY. The audit trail.
    op.create_table(
        "workflow_events",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("case_id", sa.Integer(), nullable=False),
        sa.Column("interaction_id", sa.Integer(), nullable=True),
        sa.Column("node", sa.String(length=32), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=True),
        sa.Column("to_state", sa.String(length=32), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["interaction_id"], ["interactions.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_workflow_events_case_id", "workflow_events", ["case_id"])
    op.create_index("ix_workflow_events_interaction_id", "workflow_events", ["interaction_id"])


def downgrade() -> None:
    # Reverse dependency order.
    op.drop_table("workflow_events")
    op.drop_table("follow_ups")
    op.drop_table("interventions")
    op.drop_table("human_reviews")
    op.drop_table("alerts")
    op.drop_table("risk_predictions")
    op.drop_table("risk_assessments")
    op.drop_table("reports")
    op.drop_table("interaction_analyses")
    op.drop_table("conversation_messages")
    op.drop_table("interactions")
    op.drop_table("cases")
    op.drop_table("staff_users")
    op.drop_table("consents")
    op.drop_table("users")
