"""Seed the database with staff and three controlled cases.

These are ordinary accounts with ordinary names. Nothing user-facing describes
them as demo, test or seed data — `is_controlled_test` is internal only, is
never returned by any endpoint, and is excluded from aggregates.

The three cases exercise different workflow paths:
  Meera   — settled, low state, improving
  Sunita  — moderate concern, threat present, worsening
  Kavita  — high/critical-capable, escalating trajectory

History is generated by running the REAL assessment pipeline over realistic
signal sets, so every score, baseline, trend and factor is genuinely computed
rather than typed in. Reports here are indistinguishable from live ones.

Run:  cd backend && python -m app.seed
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import select

from app.core.database import SessionLocal, init_db
from app.core.security import hash_password
from app.models import Case, ConversationMessage, Interaction, StaffUser, User
from app.services import assessment
from app.services.conversation import normalise

logging.basicConfig(level=logging.INFO, format="%(levelname)s :: %(message)s")
logger = logging.getLogger("seed")

STAFF_EMAIL = "caseworker@viora.local"
STAFF_PASSWORD = "viora1234"  # local development only


def _signals(
    *,
    distress: dict[str, float] | None = None,
    threat: dict[str, float] | None = None,
    protective: dict[str, float] | None = None,
    crisis: dict[str, Any] | None = None,
    summary: str = "",
    turns: int = 6,
    avg_chars: float = 110.0,
    depth: str = "MEDIUM",
) -> dict[str, Any]:
    def block(d: dict[str, float] | None) -> dict[str, Any]:
        return {
            k: {"present": True, "intensity": v, "evidence": ""}
            for k, v in (d or {}).items()
        }

    return normalise(
        {
            "language_detected": "hi",
            "distress_signals": block(distress),
            "threat_signals": block(threat),
            "protective_signals": block(protective),
            "engagement": {"disclosure_depth": depth, "cooperativeness": 0.8},
            "crisis": crisis or {},
            "summary": summary,
        },
        turn_count=turns,
        avg_user_chars=avg_chars,
    )


# Each entry: (days_ago, signals, [(role, content), ...])
MEERA_HISTORY = [
    (
        28,
        _signals(
            distress={"sleep_disturbance": 0.5, "anxiety_fear": 0.4, "sadness_low_mood": 0.3},
            protective={"family_support": 0.6},
            summary="Reports difficulty sleeping and ongoing worry, but describes steady support from her sister. No new incidents mentioned.",
        ),
        [
            ("VIORA", "नमस्ते मीरा। आप कैसा महसूस कर रही हैं इन दिनों?"),
            ("USER", "ठीक हूँ, पर रात को नींद नहीं आती।"),
            ("VIORA", "नींद न आना बहुत थका देता है। कब से ऐसा हो रहा है?"),
            ("USER", "जब से केस शुरू हुआ। दीदी साथ रहती हैं, वो संभाल लेती हैं।"),
            ("VIORA", "अच्छा है कि दीदी आपके साथ हैं। और कोई परेशानी?"),
            ("USER", "नहीं, बाकी ठीक है।"),
        ],
    ),
    (
        14,
        _signals(
            distress={"sleep_disturbance": 0.4, "anxiety_fear": 0.3},
            protective={"family_support": 0.7, "legal_progress": 0.5},
            summary="Sleep has improved somewhat. Describes the legal process moving forward, which she says has reduced her worry.",
        ),
        [
            ("VIORA", "नमस्ते मीरा। पिछली बार आपने नींद की बात की थी — अब कैसा है?"),
            ("USER", "थोड़ा बेहतर है। वकील साहब ने कहा केस आगे बढ़ रहा है।"),
            ("VIORA", "यह सुनकर अच्छा लगा। और घर पर सब कैसा है?"),
            ("USER", "ठीक है, दीदी हैं ना।"),
        ],
    ),
    (
        3,
        _signals(
            distress={"sleep_disturbance": 0.3},
            protective={"family_support": 0.7, "legal_progress": 0.6, "community_support": 0.4},
            summary="Describes sleeping better and feeling more settled. Mentions support from neighbours as well as family.",
            avg_chars=95.0,
        ),
        [
            ("VIORA", "नमस्ते मीरा। इस हफ्ते कैसा रहा?"),
            ("USER", "अच्छा रहा। नींद भी आ रही है अब।"),
            ("VIORA", "यह अच्छी बात है। कुछ और जो आपको परेशान कर रहा हो?"),
            ("USER", "नहीं, अभी ठीक लग रहा है। पड़ोसी भी मदद करते हैं।"),
        ],
    ),
]

SUNITA_HISTORY = [
    (
        30,
        _signals(
            distress={"anxiety_fear": 0.5, "sleep_disturbance": 0.4, "shame_stigma": 0.4},
            threat={"social_boycott": 0.5, "institutional_inaction": 0.4},
            summary="Describes being avoided by others in her village and frustration that her complaint has not progressed.",
        ),
        [
            ("VIORA", "नमस्ते सुनीता। आप कैसी हैं?"),
            ("USER", "गाँव में कोई बात नहीं करता अब। सब कतराते हैं।"),
            ("VIORA", "यह बहुत अकेला कर देने वाला होगा। थाने से कोई खबर आई?"),
            ("USER", "नहीं, बस चक्कर लगवाते हैं।"),
        ],
    ),
    (
        18,
        _signals(
            distress={"anxiety_fear": 0.6, "sleep_disturbance": 0.5, "shame_stigma": 0.5, "social_withdrawal": 0.4},
            threat={"social_boycott": 0.6, "institutional_inaction": 0.5, "economic_coercion": 0.4},
            summary="Reports increased isolation and that work has become harder to find. Continued frustration with lack of progress on her complaint.",
        ),
        [
            ("VIORA", "नमस्ते सुनीता। पिछली बार से कुछ बदला?"),
            ("USER", "काम मिलना भी बंद हो गया है। लोग मना कर देते हैं।"),
            ("VIORA", "यह बहुत मुश्किल है। घर चलाने में दिक्कत हो रही है?"),
            ("USER", "हाँ। और बाहर निकलने का मन भी नहीं करता।"),
        ],
    ),
    (
        6,
        _signals(
            distress={"anxiety_fear": 0.7, "sleep_disturbance": 0.6, "shame_stigma": 0.5, "social_withdrawal": 0.6, "hopelessness": 0.4},
            threat={"social_boycott": 0.7, "institutional_inaction": 0.6, "economic_coercion": 0.5, "intimidation_pressure": 0.5},
            summary="Reports being pressured by others to withdraw her complaint. Describes worsening isolation, disturbed sleep and reduced hope that anything will change.",
            avg_chars=140.0,
            depth="HIGH",
        ),
        [
            ("VIORA", "नमस्ते सुनीता। इस बार कैसा चल रहा है?"),
            ("USER", "कुछ लोग आए थे। कह रहे थे केस वापस ले लो, वरना ठीक नहीं होगा।"),
            ("VIORA", "यह सुनकर मुझे चिंता हो रही है। आपने यह किसी को बताया?"),
            ("USER", "किसे बताऊँ? पुलिस तो सुनती ही नहीं।"),
            ("VIORA", "आप अकेली नहीं हैं इसमें। घर पर आप खुद को सुरक्षित महसूस करती हैं?"),
            ("USER", "घर पर ठीक है, पर बाहर डर लगता है।"),
        ],
    ),
]

KAVITA_HISTORY = [
    (
        24,
        _signals(
            distress={"anxiety_fear": 0.5, "sleep_disturbance": 0.5},
            threat={"perpetrator_proximity": 0.5, "intimidation_pressure": 0.4},
            summary="Reports that the accused lives nearby and she encounters him regularly. Describes disturbed sleep and constant alertness.",
        ),
        [
            ("VIORA", "नमस्ते कविता। आप कैसी हैं आजकल?"),
            ("USER", "वो आदमी पास ही रहता है। रोज़ दिख जाता है।"),
            ("VIORA", "रोज़ सामना होना बहुत भारी होगा। नींद कैसी है आपकी?"),
            ("USER", "टूट-टूट कर आती है।"),
        ],
    ),
    (
        12,
        _signals(
            distress={"anxiety_fear": 0.7, "sleep_disturbance": 0.6, "hopelessness": 0.4, "somatic_complaints": 0.4},
            threat={"perpetrator_proximity": 0.7, "intimidation_pressure": 0.6, "direct_threat_received": 0.5},
            summary="Reports receiving threatening messages. Describes heightened fear, disturbed sleep and physical symptoms of stress.",
            depth="HIGH",
        ),
        [
            ("VIORA", "नमस्ते कविता। पिछली बार से कुछ बदला है?"),
            ("USER", "धमकी वाले मैसेज आए हैं। नाम नहीं लिखा पर समझ आता है किसने भेजे।"),
            ("VIORA", "यह गंभीर बात है। आपने वो मैसेज संभाल कर रखे हैं?"),
            ("USER", "हाँ। पर डर लगता है कि आगे क्या होगा।"),
        ],
    ),
    (
        2,
        _signals(
            distress={"anxiety_fear": 0.9, "sleep_disturbance": 0.8, "hopelessness": 0.6, "somatic_complaints": 0.5, "social_withdrawal": 0.5},
            threat={"perpetrator_proximity": 0.8, "intimidation_pressure": 0.8, "direct_threat_received": 0.8, "unsafe_at_home": 0.7, "new_incident_reported": 0.6},
            summary="Reports a new incident outside her home and escalating threats to withdraw the case. States she no longer feels safe at home. Sleep severely disturbed.",
            avg_chars=160.0,
            depth="HIGH",
        ),
        [
            ("VIORA", "नमस्ते कविता। मुझे बताइए, इस हफ्ते कैसा रहा?"),
            ("USER", "कल रात कुछ लोग घर के बाहर आए थे। चिल्ला रहे थे।"),
            ("VIORA", "यह बहुत डरावना रहा होगा। उस वक्त आपके साथ कोई था?"),
            ("USER", "माँ थीं। पर हम कुछ कर नहीं सके।"),
            ("VIORA", "आप अभी घर पर खुद को सुरक्षित महसूस कर रही हैं?"),
            ("USER", "नहीं। अब घर पर भी डर लगता है।"),
        ],
    ),
]

RAHUL_HISTORY = [
    (
        21,
        _signals(
            distress={"anxiety_fear": 0.6, "sleep_disturbance": 0.5},
            threat={"intimidation_pressure": 0.5},
            summary="Reports persistent worry about attending college and intimidation by peers trying to deter his witness testimony. Difficulty sleeping.",
            turns=4,
            avg_chars=95.0,
        ),
        [
            ("VIORA", "नमस्ते राहुल। आप कैसा महसूस कर रहे हैं आजकल?"),
            ("USER", "बहुत तनाव रहता है। कॉलेज जाने में डर लगता है।"),
            ("VIORA", "कॉलेज में डर लगना सच में बहुत मुश्किल हो सकता है। क्या किसी ने आपको डराने की कोशिश की?"),
            ("USER", "हाँ, कुछ लड़के धमकी दे रहे थे कि बयान मत देना।"),
        ],
    ),
    (
        10,
        _signals(
            distress={"anxiety_fear": 0.4, "sleep_disturbance": 0.4},
            protective={"family_support": 0.6},
            summary="Reports feeling more secure walking with his elder brother. Sleep still disrupted occasionally, but anxiety has begun easing.",
            turns=4,
            avg_chars=90.0,
        ),
        [
            ("VIORA", "नमस्ते राहुल। पिछली बार आपने कॉलेज की परेशानी बताई थी। अब कैसा है?"),
            ("USER", "भैया साथ जाते हैं तो थोड़ा ठीक लगता है। पर रात को नींद नहीं आती।"),
            ("VIORA", "यह अच्छी बात है कि भैया साथ हैं। नींद न आने पर क्या आप कुछ देर टहलते हैं या शांत बैठते हैं?"),
            ("USER", "हाँ, थोड़ी देर छत पर टहलता हूँ, फिर थोड़ा आराम मिलता है।"),
        ],
    ),
    (
        2,
        _signals(
            distress={"anxiety_fear": 0.3},
            protective={"family_support": 0.7, "community_support": 0.5, "legal_progress": 0.5},
            summary="Reports feeling substantially better after speaking with his counsellor and college administration. Routine normalizing.",
            turns=4,
            avg_chars=85.0,
        ),
        [
            ("VIORA", "नमस्ते राहुल। इस हफ्ते कैसा बीता आपका?"),
            ("USER", "पहले से बहुत बेहतर हूँ। काउंसलर सर से बात हुई और कॉलेज में भी सुरक्षा है।"),
            ("VIORA", "यह सुनकर बहुत सुकून मिला। क्या अभी कोई नई चिंता या डर है?"),
            ("USER", "नहीं, अब सब ठीक लग रहा है। पढ़ाई पर ध्यान दे पा रहा हूँ।"),
        ],
    ),
]

PEOPLE = [
    {
        "uid": "VRA-4821", "name": "Meera Devi", "language": "hi", "channel": "TEXT",
        "case_ref": "CASE-2024-0117", "stage": "Chargesheet filed",
        "safe": ("10:00", "17:00"), "history": MEERA_HISTORY,
    },
    {
        "uid": "VRA-7364", "name": "Sunita Bai", "language": "hi", "channel": "VOICE",
        "case_ref": "CASE-2024-0203", "stage": "Under investigation",
        "safe": ("11:00", "16:00"), "history": SUNITA_HISTORY,
    },
    {
        "uid": "VRA-2915", "name": "Kavita Kumari", "language": "hi", "channel": "VOICE",
        "case_ref": "CASE-2024-0288", "stage": "FIR registered",
        "safe": ("09:00", "13:00"), "history": KAVITA_HISTORY,
    },
    {
        "uid": "VRA-3108", "name": "Rahul Verma", "language": "hi", "channel": "VOICE",
        "case_ref": "CASE-2024-0315", "stage": "Witness protection support",
        "safe": ("09:00", "18:00"), "history": RAHUL_HISTORY,
    },
]


def seed() -> None:
    init_db()
    db = SessionLocal()
    try:
        staff = db.scalars(select(StaffUser)).first()
        if staff is None:
            staff = StaffUser(
                name="A. Sharma",
                email=STAFF_EMAIL,
                password_hash=hash_password(STAFF_PASSWORD),
                role="DSWO",
            )
            db.add(staff)
            db.flush()

        for person in PEOPLE:
            existing = db.scalars(select(User).where(User.uid == person["uid"])).first()
            if existing is not None:
                continue
            user = User(
                uid=person["uid"],
                display_name=person["name"],
                preferred_language=person["language"],
                preferred_channel=person["channel"],
                safe_contact_start=person["safe"][0],
                safe_contact_end=person["safe"][1],
                # Internal only. Never surfaced, never counted in aggregates.
                is_controlled_test=True,
            )
            db.add(user)
            db.flush()

            case = Case(
                user_id=user.id,
                case_ref=person["case_ref"],
                status="ACTIVE",
                legal_stage=person["stage"],
                assigned_staff_id=staff.id,
            )
            db.add(case)
            db.flush()

            for days_ago, signals, turns in person["history"]:
                when = datetime.now(timezone.utc) - timedelta(days=days_ago)

                interaction = Interaction(
                    case_id=case.id,
                    channel=person["channel"],
                    language=person["language"],
                    status="IN_PROGRESS",
                    turn_count=len(turns),
                    started_at=when,
                )
                db.add(interaction)
                db.flush()

                for seq, (role, content) in enumerate(turns, start=1):
                    db.add(
                        ConversationMessage(
                            interaction_id=interaction.id, seq=seq, role=role,
                            content=content, created_at=when,
                        )
                    )
                db.commit()

                # Real pipeline: scores, baselines, trends and factors are all
                # genuinely computed, not written in by hand.
                result = assessment.run_assessment(
                    db, interaction=interaction, raw_signals=signals,
                    model_id="seed", now=when,
                )
                logger.info(
                    "%-16s v%s  distress=%-5s threat=%-5s %-8s %s",
                    person["name"], result.report.report_version,
                    result.report.distress_score, result.report.threat_score,
                    result.risk_level, result.report.trend,
                )

        logger.info("")
        logger.info("Seed complete.")
        logger.info("  Dashboard login: %s / %s", STAFF_EMAIL, STAFF_PASSWORD)
        logger.info("  Profiles: %s", ", ".join(p["name"] for p in PEOPLE))
    finally:
        db.close()


if __name__ == "__main__":
    seed()
